name: Build

on:
  push:
    branches:
      - "build/**"
  pull_request:
  merge_group:
    types:
        - checks_requested

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: [check]
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      enabled: ${{ github.repository == 'brioche-dev/brioche-packages' && (github.event_name == 'push' || github.event_name == 'merge_group') }}
