name: CI

on:
  push:
    branches:
      - main
      - 'build/**'
      - 'live-update/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: Check packages
    runs-on: ubuntu-22.04
    # Skip jobs for PRs from `build/` and `live-update/` branches, since
    # both are already triggered by push events
    if: ! (github.event_name == 'pull_request' && (startsWith(github.head_ref, 'build/') || startsWith(github.head_ref, 'live-update/')))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Brioche
        run: |
          mkdir -p ~/.local/bin
          curl -L https://development-content.brioche.dev/github.com/brioche-dev/brioche/branches/main/x86_64-linux/brioche -o ~/.local/bin/brioche
          chmod +x ~/.local/bin/brioche
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Check packages
        run: |
          for package in packages/*; do
            echo "::group::$package"
            brioche check -p "$package" --locked
            brioche fmt -p "$package" --check
            echo "::endgroup::"
          done

  build:
    name: Build packages
    needs: [check]
    if: github.repository == 'brioche-dev/brioche-packages' && github.event_name == 'push' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/build/') || startsWith(github.ref, 'refs/heads/live-update/') )
    runs-on: brioche-dev-builder-runner
    timeout-minutes: 720
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Brioche
        run: |
          mkdir -p ~/.local/bin
          curl -L https://development-content.brioche.dev/github.com/brioche-dev/brioche/branches/main/x86_64-linux/brioche -o ~/.local/bin/brioche
          chmod +x ~/.local/bin/brioche
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Build packages
        run: |
          for package in packages/*; do
            echo "::group::$package"
            brioche build -p "$package" --sync --locked --display plain-reduced
            echo "::endgroup::"
          done
        env:
          BRIOCHE_LEGACY_REGISTRY_SYNC: "true"
          BRIOCHE_REGISTRY_PASSWORD: ${{ secrets.BRIOCHE_REGISTRY_PASSWORD }}
          BRIOCHE_CACHE_URL: ${{ vars.BRIOCHE_CACHE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.CACHE_AWS_ENDPOINT_URL_S3 }}
          AWS_REGION: ${{ vars.CACHE_AWS_REGION }}
          AWS_REQUEST_CHECKSUM_CALCULATION: WHEN_REQUIRED
          AWS_RESPONSE_CHECKSUM_CALCULATION: WHEN_REQUIRED
      - name: Run package tests
        run: |
          for package in packages/*; do
            if grep -q 'export.*test' "$package/project.bri"; then
              echo "::group::$package"
              brioche build -p "$package" -e test --sync --locked
              echo "::endgroup::"
            else
              echo "$package: no tests found"
            fi
          done
        env:
          BRIOCHE_LEGACY_REGISTRY_SYNC: "true"
          BRIOCHE_REGISTRY_PASSWORD: ${{ secrets.BRIOCHE_REGISTRY_PASSWORD }}
          BRIOCHE_CACHE_URL: ${{ vars.BRIOCHE_CACHE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.CACHE_AWS_ENDPOINT_URL_S3 }}
          AWS_REGION: ${{ vars.CACHE_AWS_REGION }}
          AWS_REQUEST_CHECKSUM_CALCULATION: WHEN_REQUIRED
          AWS_RESPONSE_CHECKSUM_CALCULATION: WHEN_REQUIRED
      - name: Save failed processes
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: process-events
          path: ~/.local/share/brioche/process-temp/*/events.bin.zst
          compression-level: 0

  publish:
    name: Publish packages
    needs: [build]
    if: github.repository == 'brioche-dev/brioche-packages' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Brioche
        run: |
          mkdir -p ~/.local/bin
          curl -L https://development-content.brioche.dev/github.com/brioche-dev/brioche/branches/main/x86_64-linux/brioche -o ~/.local/bin/brioche
          chmod +x ~/.local/bin/brioche
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Publish packages
        run: |
          for package in packages/*; do
            echo "::group::$package"
            brioche publish -p "$package"
            echo "::endgroup::"
          done
        env:
          BRIOCHE_REGISTRY_PASSWORD: ${{ secrets.BRIOCHE_REGISTRY_PASSWORD }}
          BRIOCHE_CACHE_URL: ${{ vars.BRIOCHE_CACHE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.CACHE_AWS_ENDPOINT_URL_S3 }}
          AWS_REGION: ${{ vars.CACHE_AWS_REGION }}
          AWS_REQUEST_CHECKSUM_CALCULATION: WHEN_REQUIRED
          AWS_RESPONSE_CHECKSUM_CALCULATION: WHEN_REQUIRED
