name: CI

on:
  - push

jobs:
  publish:
    name: Publish packages
    if: github.repository == 'brioche-dev/brioche-packages' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Brioche
        run: |
          mkdir -p ~/.local/bin
          curl -L https://development-content.brioche.dev/github.com/brioche-dev/brioche/branches/main/x86_64-linux/brioche -o ~/.local/bin/brioche
          chmod +x ~/.local/bin/brioche
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Publish projects
        run: |
          for project in projects/*; do
            echo "::group::$project"
            brioche publish -p "$project"
            echo "::endgroup::"
          done
        env:
          BRIOCHE_REGISTRY_PASSWORD: ${{ secrets.BRIOCHE_REGISTRY_PASSWORD }}
